class IDigitalMessage:
    REQUIRED_SESSION: str = 'O uso de sessão é obrigatório.'
    INVALID_JWT: str = 'O token em análise não é um JWT válido.'
    DIVERGENT_CLIENT_ID: str = 'O ID do cliente não pertence ao servidor.'
    DIVERGENT_NONCE: str = 'A propriedade nonce enviada difere da armazenada.'
    DIVERGENT_STATE: str = 'A propriedade state enviada difere da armazenada.'
    DIVERGENT_ISSUER: str = 'A propriedade issuer enviada difere da armazenada.'
    COULD_NOT_GENERATE_PKCE: str = 'O servidor não conseguiu gerar as chaves PKCE.'
    DIVERGENT_AUDIENCE: str = 'A propriedade audience enviada difere da armazenada.'
    JWT_WITHOUT_ALG: str = 'O JWT não possui uma propriedade alg válida no cabeçalho.'
    JWT_WITHOUT_KID: str = 'O JWT não possui uma propriedade kid válida no cabeçalho.'
    JWT_WITHOUT_TYP: str = 'O JWT não possui uma propriedade typ válida no cabeçalho.'
    COULD_NOT_GENERATE_BYTES: str = 'O servidor não conseguiu gerar valores aleatórios.'
    HTTP_ERROR: str = 'Não foi possível realizar a requisição para o servidor de destino.'
    COULD_NOT_FIND_PUBLIC_KEYS: str = 'O servidor não conseguiu encontrar chaves públicas.'